name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, osfitsiomax-vps]

    steps:
      - name: Deploy to VPS
        run: bash /root/deploy-osfitsiomax.sh
